sudo: required

services:
  - docker

before_install:
  - docker build -t cinhtau/docker-kafka-manager .

script:
  - docker images cinhtau/docker-kafka-manager

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push cinhtau/docker-kafka-manager;
    fi